######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 1 10:13:19 2016
######################################################################

TEMPLATE = app
TARGET = QtE-Demo
DEPENDPATH += .
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += mainwidget.h util.h boardtype_test.h
SOURCES += main.cpp mainwidget.cpp util.cpp boardtype_test.cpp
RESOURCES += main.qrc
