######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 1 10:13:19 2016
######################################################################

TEMPLATE = app
TARGET = QtE-Demo
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwidget.h util.h boardtype_friendlyelec.h tft28lcd.h
SOURCES += main.cpp mainwidget.cpp util.cpp boardtype_friendlyelec.cpp tft28lcd.cpp
RESOURCES += main.qrc
